### ISSUE TITLE
你好, 今天使用了您的身份证校验信息包, 中间出现一个小bug, 身份证信息: 230106199202099035 这个身份证号是错误的, 包里在运行zone方法时报错,我查了下代码, 是codes.php里面没有230106的值, 所以才会报错, 方法定义返回string, 没有考虑不存在, 身份证号异常的情况处理, 报错如下:

### ISSUE THREAD

**Issue by jierui303** [yangliulnn/id-card#6]
你好, 今天使用了您的身份证校验信息包, 中间出现一个小bug,
身份证信息: 230106199202099035
这个身份证号是错误的, 包里在运行zone方法时报错,我查了下代码, 是codes.php里面没有230106的值, 所以才会报错, 方法定义返回string, 没有考虑不存在, 身份证号异常的情况处理, 报错如下:
``
An uncaught Exception was encountered
Type: TypeError

Message: Return value of Leonis\IDCard\IDCard::zone() must be of the type string, null returned

Filename: /vagrant/XCX_BJD/vendor/leonis/id-card/src/IDCard.php

Line Number: 121

Backtrace:

File: /vagrant/XCX_BJD/vendor/leonis/id-card/src/IDCard.php
Line: 90
Function: zone

File: /vagrant/XCX_BJD/application/controllers/Test.php
Line: 644
Function: address

File: /vagrant/XCX_BJD/index.php
Line: 293
Function: require_once`
```


代码位置: 
```
 /**
     * 获取区.
     *
     * @return string
     */
    public function zone() : string
    {
//        return isset($this->areaCodes[substr($this->id, 0, 6)]) ? $this->areaCodes[substr($this->id, 0, 6)] : '';
        return $this->areaCodes[substr($this->id, 0, 6)];
    }
```

**Comment by jierui303** [comment]
谢谢您提供的插件包, 用起来很方便, 希望您能后期维护一下,Thanks♪(･ω･)ﾉ

**Comment by yangliulnn** [comment]
@jierui303 
最新版本已修复：release 2.0.3
